name: Docker Publish

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute image name
        id: meta
        run: |
          IMAGE_REPO="${{ vars.DOCKERHUB_REPOSITORY }}"
          if [ -z "$IMAGE_REPO" ]; then
            if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
              echo "::error::Please set secrets.DOCKERHUB_USERNAME or vars.DOCKERHUB_REPOSITORY" && exit 1
            fi
            IMAGE_REPO="${{ secrets.DOCKERHUB_USERNAME }}/telegram-forwarder"
          fi
          echo "IMAGE_REPO=$IMAGE_REPO" >> $GITHUB_ENV
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            echo "VERSION_TAG=$TAG" >> $GITHUB_ENV
          fi

      - name: Build and push (latest)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_REPO }}:latest

      - name: Build and push (version tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_REPO }}:${{ env.VERSION_TAG }}

